PATCH  http://localhost:3001/api/notes/63ede5eb9b9a7e02c0ee4578
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldiIsImlkIjoiNjNlZGYxMzNmYzQ2ZGRhYzkzNGM0MDYxIiwiaWF0IjoxNjc2NTQwMjkyLCJleHAiOjE2NzY1NTEwOTJ9.CiHkv6mW29gNcmp2jcbh2cXBov4AAJkqDbb559lYyxk
Content-Type: application/json

{
    "title":"first edited title",
    "body":"edited body too"
}